import { VerifiedIcon } from "lucide-react";
import {
  IoAlarmOutline,
  IoAlert,
  IoArrowUpCircleOutline,
  IoAttachOutline,
  IoBedOutline,
  IoCalendarClearOutline,
  IoCalendarOutline,
  IoChatboxOutline,
  IoCheckmark,
  IoCheckmarkCircleOutline,
  IoChevronDownOutline,
  IoCloseOutline,
  IoCloudDownloadOutline,
  IoCopyOutline,
  IoDocumentOutline,
  IoDocumentsOutline,
  IoDocumentTextOutline,
  IoEyeOutline,
  IoFileTrayOutline,
  IoHappyOutline,
  IoHomeOutline,
  IoIdCardOutline,
  IoInformation,
  IoLayersOutline,
  IoLinkOutline,
  IoLogInOutline,
  IoLogOutOutline,
  IoMenuOutline,
  IoNotificationsOutline,
  IoPeopleCircleOutline,
  IoPersonCircleOutline,
  IoPrintOutline,
  IoReaderOutline,
  IoReceiptOutline,
  IoRefreshOutline,
  IoRepeatOutline,
  IoSchoolOutline,
  IoSearchOutline,
  IoSendOutline,
  IoSwapHorizontalOutline,
  IoWalletOutline,
} from "react-icons/io5";
import type { IconBaseProps } from "react-icons/lib";

export const Icons = {
  warning: IoAlert,
  bed: IoBedOutline,
  eye: IoEyeOutline,
  copy: IoCopyOutline,
  home: IoHomeOutline,
  info: IoInformation,
  link: IoLinkOutline,
  menu: IoMenuOutline,
  send: IoSendOutline,
  success: IoCheckmark,
  close: IoCloseOutline,
  happy: IoHappyOutline,
  logIn: IoLogInOutline,
  print: IoPrintOutline,
  verified: VerifiedIcon,
  idCard: IoIdCardOutline,
  layers: IoLayersOutline,
  logOut: IoLogOutOutline,
  school: IoSchoolOutline,
  reader: IoReaderOutline,
  search: IoSearchOutline,
  wallet: IoWalletOutline,
  repeat: IoRepeatOutline,
  reminder: IoAlarmOutline,
  attached: IoAttachOutline,
  receipt: IoReceiptOutline,
  refresh: IoRefreshOutline,
  chatbox: IoChatboxOutline,
  document: IoDocumentOutline,
  fileTray: IoFileTrayOutline,
  calendar: IoCalendarOutline,
  date: IoCalendarClearOutline,
  documents: IoDocumentsOutline,
  arrowUp: IoArrowUpCircleOutline,
  chevronDown: IoChevronDownOutline,
  checkmark: IoCheckmarkCircleOutline,
  documentText: IoDocumentTextOutline,
  personCircle: IoPersonCircleOutline,
  peopleCirlcle: IoPeopleCircleOutline,
  notification: IoNotificationsOutline,
  cloudDownload: IoCloudDownloadOutline,
  swapHorizontal: IoSwapHorizontalOutline,
};

type Props = {
  active?: boolean;
  name: keyof typeof Icons;
};

export default function Icon(props: Props & IconBaseProps) {
  const { name } = props;
  const IconComponent = Icons[name];

  return IconComponent ? <IconComponent {...props} /> : null;
}
