import type { UnitsPerSemester } from "./columns";

export const normalUnits: UnitsPerSemester[] = [
  {
    program: "BSCS",
    stage: "Y1S1",
    semester: "Semester 1",
    regFor: "2024/2025",
    modeOfStudy: "Full-time",
    unitsTaken: 6,
  },
  {
    program: "BSCS",
    stage: "Y1S2",
    semester: "Semester 2",
    regFor: "2024/2025",
    modeOfStudy: "Full-time",
    unitsTaken: 7,
  },
  {
    program: "BSCS",
    stage: "Y1S3",
    semester: "Semester 3",
    regFor: "2024/2025",
    modeOfStudy: "Full-time",
    unitsTaken: 5,
  },
  {
    program: "BSCS",
    stage: "Y2S1",
    semester: "Semester 1",
    regFor: "2025/2026",
    modeOfStudy: "Full-time",
    unitsTaken: 6,
  },
  {
    program: "BSCS",
    stage: "Y2S2",
    semester: "Semester 2",
    regFor: "2025/2026",
    modeOfStudy: "Full-time",
    unitsTaken: 6,
  },
  {
    program: "BSCS",
    stage: "Y2S3",
    semester: "Semester 3",
    regFor: "2025/2026",
    modeOfStudy: "Full-time",
    unitsTaken: 5,
  },
  {
    program: "BSCS",
    stage: "Y3S1",
    semester: "Semester 1",
    regFor: "2026/2027",
    modeOfStudy: "Full-time",
    unitsTaken: 7,
  },
  {
    program: "BSCS",
    stage: "Y3S2",
    semester: "Semester 2",
    regFor: "2026/2027",
    modeOfStudy: "Full-time",
    unitsTaken: 6,
  },
  {
    program: "BSCS",
    stage: "Y3S3",
    semester: "Semester 3",
    regFor: "2026/2027",
    modeOfStudy: "Full-time",
    unitsTaken: 5,
  },
  {
    program: "BSCS",
    stage: "Y4S1",
    semester: "Semester 1",
    regFor: "2027/2028",
    modeOfStudy: "Full-time",
    unitsTaken: 6,
  },
  {
    program: "BSCS",
    stage: "Y4S2",
    semester: "Semester 2",
    regFor: "2027/2028",
    modeOfStudy: "Full-time",
    unitsTaken: 6,
  },
  {
    program: "BSCS",
    stage: "Y4S3",
    semester: "Semester 3",
    regFor: "2027/2028",
    modeOfStudy: "Full-time",
    unitsTaken: 4,
  },
];

export const supplementaryUnits: UnitsPerSemester[] = [
  {
    program: "BSCS",
    stage: "Y3S1",
    semester: "Semester 1",
    regFor: "2026/2027",
    modeOfStudy: "Supplementary",
    unitsTaken: 1,
  },
  {
    program: "BSCS",
    stage: "Y4S1",
    semester: "Semester 1",
    regFor: "2027/2028",
    modeOfStudy: "Supplementary",
    unitsTaken: 2,
  },
];

export const retakeUnits: UnitsPerSemester[] = [];
